[tool.poetry]
name = "streamlit-flow-sid"
version = "0.1.0"
description = ""
authors = ["siddhardha sukka"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
streamlit = "^1.40.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
